[project]
name = "elara-rag-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "bcrypt>=5.0.0",
    "docling>=2.120.1",
    "docling-core>=2.91.0",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "groq>=1.6.0",
    "jwt>=1.4.0",
    "mongomock-motor>=0.0.36",
    "motor>=3.7.1",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "pymongo[srv]>=4.17.0",
    "pypdf>=6.16.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "python-multipart>=0.0.32",
    "qdrant-client>=1.19.0",
    "reportlab>=5.0.0",
    "sentence-transformers>=5.7.0",
    "uvicorn>=0.52.3",
]
