name: Elara-CI-Pipeline

on:
  push:
    branches: [backend, master]
    paths:
    - 'src/**'
    - 'pyproject.toml'
    - 'tests/**'
    - '.github/workflows/**'
  pull-request:
    branches: [backend, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
      - uses: action/checkout@v4

      - name: Set up python
      - uses:
